spring:
  security:
    oauth2:
      client:
        registration:

          google:
            client-id: 372166745817-oi02rm27mihcnglp4cq4f0aduok7chdt.apps.googleusercontent.com
            client-secret: YOUR_GOOGLE_CLIENT_SECRET
            scope:
              - email
              - profile

          github:
            client-id: YOUR_GITHUB_CLIENT_ID
            client-secret: YOUR_GITHUB_CLIENT_SECRET
            scope:
              - user:email